export const ROLE_GOOD = 'ROLE_GOOD'
export const ROLE_EVIL = 'ROLE_EVIL'
export const ROLE_MERLIN = 'ROLE_MERLIN'
export const ROLE_ASSASSIN = 'ROLE_ASSASSIN'
export const ROLE_PERCIVAL = 'ROLE_PERCIVAL'
export const ROLE_MORGANA = 'ROLE_MORGANA'
export const ROLE_MORDRED = 'ROLE_MORDRED'
export const ROLE_OBERON = 'ROLE_OBERON'