export const HOST_GAME_REQUEST = 'HOST_GAME_REQUEST'
export const HOST_GAME_SUCCESS = 'HOST_GAME_SUCCESS'
export const START_SETUP_REQUEST = 'START_SETUP_REQUEST'
export const START_SETUP_SUCCESS = 'START_SETUP_SUCCESS'
export const START_SETUP_FAILURE = 'START_SETUP_FAILURE'

export const JOIN_GAME_REQUEST = 'JOIN_GAME_REQUEST'
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS'
export const JOIN_GAME_FAILURE = 'JOIN_GAME_FAILURE'

export const UPDATE_PLAYERS = 'UPDATE_PLAYERS'

export const SET_NAME_REQUEST = 'SET_NAME_REQUEST'
export const SET_NAME_FAILURE = 'SET_NAME_FAILURE'
export const SET_NAME_SUCCESS = 'SET_NAME_SUCCESS'