export const HOST_GAME_REQUEST = 'HOST_GAME_REQUEST'
export const HOST_GAME_SUCCESS = 'HOST_GAME_SUCCESS'
export const START_SETUP_REQUEST = 'START_SETUP_REQUEST'
export const START_SETUP_SUCCESS = 'START_SETUP_SUCCESS'
export const START_SETUP_FAILURE = 'START_SETUP_FAILURE'

export const JOIN_GAME_REQUEST = 'JOIN_GAME_REQUEST'
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS'
export const JOIN_GAME_FAILURE = 'JOIN_GAME_FAILURE'

export const UPDATE_PLAYERS = 'UPDATE_PLAYERS'

export const SET_NAME_REQUEST = 'SET_NAME_REQUEST'
export const SET_NAME_FAILURE = 'SET_NAME_FAILURE'
export const SET_NAME_SUCCESS = 'SET_NAME_SUCCESS'

export const SUBMIT_RULES_REQUEST = 'SUBMIT_RULES_REQUEST'
export const SUBMIT_RULES_FAILURE = 'SUBMIT_RULES_FAILURE'

export const UPDATE_QUESTS = 'UPDATE_QUESTS'

export const GIVE_PLAYER_INFO = 'GIVE_PLAYER_INFO'

export const START_PARTY_SELECTION = 'START_PARTY_SELECTION'
export const SELECT_PARTY_MEMBER_REQUEST = 'SELECT_PARTY_MEMBER_REQUEST'
export const SELECT_PARTY_MEMBER_FAILURE = 'SELECT_PARTY_MEMBER_FAILURE'
export const REMOVE_PARTY_MEMBER_REQUEST = 'REMOVE_PARTY_MEMBER_REQUEST'
export const REMOVE_PARTY_MEMBER_FAILURE = 'REMOVE_PARTY_MEMBER_FAILURE'
